### ISSUE TITLE
Add an option to sort task alphabatically

### ISSUE THREAD

**Issue by Jenselme** [sttk/gulp-showhelp#4]
I saw that if you list the task in the show method they will be listed in the specified order. However, I would just like to see them in alphabetical order.

Is it possible to add an option to do that?

**Comment by sttk** [comment]
I've added 2 APIs on version 1.0.3: .taskNames() and .show(string[]).

You can write as follows to see tasks in alphabetical order in a help message:

```js
ghelp.show(ghelp.taskNames().sort());
```

**Comment by Jenselme** [comment]
Awsome! Thanks.
